fixed_circuit.txt : ../../circuit_fixup.py public_input expected_output aes_128.txt
	python ../../circuit_fixup.py aes_128.txt public_input expected_output > fixed_circuit.txt

public_input expected_output key : generate_key_input_output.py
	python generate_key_input_output.py
